
version: "3.0"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb1
    environment:
      MONGO_REPLICA_SET_NAME: rsmongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    command:
      [
        "--bind_ip_all",
        "--replSet",
        "rsmongo",
        "--dbpath",
        "/data/db"
      ]
    volumes:
      - mongodata1:/data/db # This is where your volume will persist. e.g. VOLUME-DIR = ./volumes/mongodb
      - mongoconfig:/data/configdb
    deploy:
      restart_policy:
        condition: on-failure
  mongo-setup:
    image: mongo-setup
    build: "./mongo"
    container_name: mongo-setup
    environment:
      TTL_DOCUMENT: 3600 # documents are automatically deleted after 3600 seconds ~ 1 h
      MONGO_HOST: mongodb1
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    volumes:
      - mongodata2:/data
volumes:
  mongodata1:
  mongoconfig:
  mongodata2: