files = [
    { type = "software-management", path = "/var/log/tedge/agent/software-*" },
    { type = "mosquitto", path = "/var/log/mosquitto/mosquitto.log" },
    { type = "tedge-agent", path = "/var/log/tedge-agent.log" },
    { type = "tedge-mapper-collectd", path = "/var/log/tedge-mapper-collectd.log" },
    { type = "tedge-mapper-c8y", path = "/var/log/tedge-mapper-c8y.log" },
    { type = "management-ui", path = "/var/log/tedge-ui/tedge-ui.log" },
]